### PR TITLE
Feature: We have basic read/write functionality to a Firebase database

### PR DESCRIPTION
**Pull request by christoffles**

### CODE REVIEW

**Comment by ghost** [comment]
I think we should have a standard for commit messages. Maybe [this](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). Summary in title and body should go in detail on what you did.

**Comment by christoffles** [comment]
approve and i'll fix it when i squash

**Comment by ghost** [comment]
Approved

**Comment by ghost** [comment]
Ok can’t do it in the phone lol

**Review by ghost — APPROVED** [review]

**Pull request merged**
